# Generated by Django 6.0.4 on 2026-05-05 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prime_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prime_rendement', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(default='actif', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotisation_cnps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
