# Generated by Django 6.0.4 on 2026-05-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='plat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.plat'),
            preserve_default=False,
        ),
    ]
