# Generated by Django 6.0.4 on 2026-05-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_lignecommande_plat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_pct', models.FloatField(default=19.25)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.commande')),
            ],
        ),
    ]
