# Generated by Django 6.0.3 on 2026-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèce'), ('carte', 'Carte Bancaire'), ('momo', 'MTN Mobile Money'), ('orange', 'Orange Money')], default='espece', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('sur_place', 'Sur place'), ('livraison', 'Livraison'), ('emporter', 'À emporter')], default='sur_place', max_length=20),
        ),
    ]
