# Generated by Django 6.0.4 on 2026-05-05 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nouveau_prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='products.plat')),
            ],
        ),
    ]
