# Generated by Django 6.0.4 on 2026-05-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_salaire_salaire_net_affectation'),
        ('inventory', '0001_initial'),
        ('products', '0002_historiqueprix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_cuisson', models.IntegerField(help_text='Temps de cuisson en minutes')),
                ('instructions', models.TextField(blank=True)),
                ('chef_en_charge', models.ForeignKey(limit_choices_to={'poste__icontains': 'chef'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('plat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recette', to='products.plat')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_requise', models.FloatField(help_text='Quantité requise pour un plat')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.recette')),
            ],
        ),
    ]
